enum NOTIFICATION_TYPE {
  REVIEWING
}

type Notification {
  "Notification unique id"
  id: String!

  "Notification type"
  type: NOTIFICATION_TYPE!

  "Notification title"
  title: String!

  "Notification description"
  description: String!

  "Flag to define whether the notification is activate or not"
  isActive: Boolean!

  "Notification created date and time"
  createdAt: DateTime!

  "Notification updated date and time"
  updatedAt: DateTime
}

input InputNotification {
  "Notification role"
  type: NOTIFICATION_TYPE!

  "Notification title"
  title: String!

  "Notification description"
  description: String!
}

# ----------------------------------------------------

type Mutation {
  "Create a new notification"
  createNotification(data: InputNotification!): Notification

  "Update specific notification"
  updateNotification(id: String!, isActive: Boolean!): Notification
}